/**
 * Semantic Identity, Role & Merge Review — Sprint12-E4, extended
 * Sprint12-E5, restructured Sprint12-E6.
 *
 * Sits between the Semantic Provider's raw proposals and the
 * (unmodified — see §K) proposal-level Structural Validator:
 *
 *   Interpretation Proposals -> Identity Review -> Structural Validator
 *
 * Scope: ONLY `updatedElements`. A ProposedUpdate is an implicit "this
 * is the SAME referent as targetElementId" claim.
 *
 * Sprint12-E5 §1/§2: introduced a 4-way decision (SAME_ELEMENT /
 * SAME_REALITY_DIFFERENT_ELEMENT / SEPARATE_REALITY / UNCERTAIN) and
 * PROMOTES a reclassified update into a real newElement (+ optional
 * relation) instead of only ever holding evidence in `unresolved`
 * forever. Promotion never invents content: the new element's kind
 * comes from the Interpreter's own `impliedElementKind` (types.ts),
 * and its description/evidence come from the update proposal's own
 * groundingText — all already generated by the Interpreter.
 *
 * Sprint12-E5 report found UNCERTAIN essentially unreachable (0/15 on
 * the ambiguity gate, 0/36 in the real 12-CASE runs) — flattening
 * "can this be decided" into a 4th co-equal enum value alongside three
 * richly-defined confident options gave the model nothing preventing
 * it from treating a 4-way choice as "pick the least-committal
 * confident label" rather than "first ask whether you can decide at
 * all." Sprint12-E6 §4 splits this into two explicit steps instead:
 * DECIDABILITY first (can this be decided from the evidence at all?),
 * then — only if DECIDABLE — a 3-way IdentityDecision. This is still
 * ONE reviewer call (Sprint12-E6 §9 Option A — see report §C for why),
 * just with `decidability` structurally required BEFORE `decision` in
 * the Reviewer's own output schema, so the model reasons about
 * decidability before ever committing to a label.
 *
 * This module still does NOT re-implement any lexical/token check
 * (Sprint12-E3 §10) — every decision here is a semantic judgment made
 * by a SemanticIdentityReviewer implementation and trusted as a typed
 * decision, never re-derived from its own free-text `note`.
 */
import type {
  ContextElement,
  ContextGraph,
  ContextGraphSummary,
  ElementKind,
  InterpreterOutput,
  ProposedElement,
  ProposedRelation,
  ProposedUnresolved,
  ProposedUpdate,
  RelationType,
} from "./types";
import { summarizeGraph } from "./types";

/**
 * Sprint12-E6 §4/§10/§11: DECIDABLE means the evidence itself settles
 * the identity question without assuming anything the user didn't say.
 * NOT_DECIDABLE is not "the model found this hard" — it is the honest
 * report that multiple relationships are genuinely, equally plausible
 * given only the text provided.
 */
export type Decidability = "DECIDABLE" | "NOT_DECIDABLE";

/** UNCERTAIN removed from this enum (Sprint12-E6 §4) — "cannot decide"
 *  is now Decidability's job, not a 4th identity label. */
export type IdentityDecision = "SAME_ELEMENT" | "SAME_REALITY_DIFFERENT_ELEMENT" | "SEPARATE_REALITY";

export type IdentityReviewInput = {
  currentTurn: number;
  currentTurnText: string;
  /** The update proposal under review, exactly as the Provider proposed it. */
  candidateUpdate: ProposedUpdate;
  /** The existing element's full current state — not a summary, since
   *  the Reviewer needs the real description to judge referent identity. */
  targetElement: ContextElement;
  /** Other currently active elements, for contrast only (Sprint12-E4
   *  §6) — summarized, not full evidence dumps. */
  nearbyActiveElements: ContextGraphSummary["elements"];
};

export type IdentityReviewOutput = {
  decidability: Decidability;
  /**
   * Present only when decidability is "DECIDABLE". Sprint12-E6 §10
   * invariant, enforced structurally here (not just by prompt
   * compliance): even if an adapter's raw wire format always carries
   * some value (OpenAI strict JSON schema requires every declared
   * field to always be populated), this type — and every orchestration
   * function below — MUST treat `decision` as absent/meaningless
   * whenever decidability is NOT_DECIDABLE. See
   * semanticIdentityReviewerAdapter.ts's mapping for where the raw
   * value gets stripped.
   */
  decision?: IdentityDecision;
  /** Observational only (Sprint12-E4 §18) — never gates behavior. */
  confidence: number;
  /** Debugging aid only. Never re-parsed or treated as truth (§8). */
  note?: string;
  /**
   * Sprint12-E5 §19: only meaningful (and only ever used) when decision
   * is SAME_REALITY_DIFFERENT_ELEMENT. Optional — if the Reviewer has
   * no specific evidence for a stronger relation, orchestration below
   * falls back to the minimal, always-structurally-justified
   * "relatesTo".
   */
  suggestedRelationType?: RelationType;
};

export interface SemanticIdentityReviewer {
  review(input: IdentityReviewInput): Promise<IdentityReviewOutput>;
}

export type IdentityReviewLogEntry = {
  targetElementId: string;
  decidability: Decidability;
  decision?: IdentityDecision;
  confidence: number;
  note?: string;
};

const VALID_RELATION_TYPES = new Set<RelationType>(["limits", "supports", "conflictsWith", "respondsTo", "clarifies", "revises", "relatesTo"]);

/**
 * Sprint12-E5 §16/§18, unchanged in Sprint12-E6 §32: mechanical,
 * information-preserving promotion — no field here is invented by this
 * module. `kind`/description/evidence all come straight from fields
 * the Interpreter already produced on the update proposal itself.
 * Uses `groundingText`, NOT `note`, as the description (Sprint12-E5
 * report §V/§AG — `note` has no language-consistency guarantee and
 * caused silent evidence loss; `groundingText` is Contract-required to
 * be a literal, source-language quote). This is protected this Sprint
 * (§32 "note 기반 description으로 되돌리지 않는다").
 */
function toPromotedElement(u: ProposedUpdate, localRef: string): ProposedElement {
  return {
    localRef,
    kind: u.impliedElementKind as ElementKind,
    description: u.groundingText,
    groundingTurn: u.groundingTurn,
    groundingText: u.groundingText,
    confidence: u.confidence,
  };
}

function toPromotionRelation(u: ProposedUpdate, promotedLocalRef: string, targetConfidence: number, suggestedType: RelationType | undefined): ProposedRelation {
  const type = suggestedType && VALID_RELATION_TYPES.has(suggestedType) ? suggestedType : "relatesTo";
  return {
    type,
    from: promotedLocalRef,
    to: u.targetElementId,
    groundingTurn: u.groundingTurn,
    groundingText: u.groundingText,
    // V5 requires relation.confidence <= min(endpoint confidences).
    confidence: Math.min(u.confidence, targetConfidence),
  };
}

/**
 * Sprint12-E4 §15 option B / Sprint12-E5 §11/§16, now triggered by
 * NOT_DECIDABLE instead of the old UNCERTAIN label (Sprint12-E6 §20
 * "NOT_DECIDABLE → HOLD + PRESERVE"): held back from merge as an
 * update (identityRelation forced to "uncertainSameElement", routes
 * through Sprint12-E3's existing merge-withholding mechanism
 * unchanged) AND mirrored into unresolvedCandidates, so the evidence
 * is structurally visible in the graph's `unresolved[]` rather than
 * only living in one turn's ephemeral PreviousProposalFeedback.
 * Never promoted — Sprint12-E6 §32 "NOT_DECIDABLE evidence는 자동
 * promotion하지 않는다": we don't yet know if this is genuinely a new
 * fact or actually belongs to the target, so creating a full element
 * would risk a confident-looking duplicate of something uncertain.
 */
function toNotDecidableUnresolved(u: ProposedUpdate): ProposedUnresolved {
  return {
    relatesTo: [u.targetElementId],
    reason: `Reviewer판단: NOT_DECIDABLE — targeted ${u.targetElementId} as an update, but the evidence does not settle whether this is the same element, a different element in the same reality, or a separate reality.`,
    groundingTurn: u.groundingTurn,
    groundingText: u.groundingText,
    uncertainty: 0.6,
    potentialInformationGain: "medium",
  };
}

/**
 * Runs identity review over one turn's updatedElements and returns a
 * reviewed InterpreterOutput of the SAME shape, ready to hand to the
 * unmodified Structural Validator exactly as Sprint12-E3/E4/E5 already
 * do.
 *
 * - NOT_DECIDABLE (checked first, Sprint12-E6 §4/§20): identityRelation
 *   forced to "uncertainSameElement" AND mirrored into
 *   unresolvedCandidates (toNotDecidableUnresolved). No merge, no
 *   promotion, no relation, no evidence deletion.
 * - DECIDABLE + SAME_ELEMENT: proposal passes through unchanged.
 * - DECIDABLE + SAME_REALITY_DIFFERENT_ELEMENT: removed from
 *   updatedElements; mechanically promoted to a newElement plus a
 *   relation to the original target.
 * - DECIDABLE + SEPARATE_REALITY: same promotion, but with NO relation
 *   to the target.
 *
 * An update whose targetElementId does not exist in `graph` is passed
 * through untouched — endpoint existence is the Structural Validator's
 * job (V1), not the Reviewer's (Sprint12-E4 §13).
 */
export async function applyIdentityReview(
  output: InterpreterOutput,
  graph: ContextGraph,
  currentTurn: number,
  currentTurnText: string,
  reviewer: SemanticIdentityReviewer,
): Promise<{ output: InterpreterOutput; log: IdentityReviewLogEntry[] }> {
  const keptUpdates: ProposedUpdate[] = [];
  const addedNewElements: ProposedElement[] = [];
  const addedRelations: ProposedRelation[] = [];
  const addedUnresolved: ProposedUnresolved[] = [];
  const log: IdentityReviewLogEntry[] = [];
  let promotionSeq = 0;

  for (const u of output.updatedElements) {
    const target = graph.elements.find((e) => e.id === u.targetElementId);
    if (!target) {
      keptUpdates.push(u);
      continue;
    }

    const nearbyActiveElements = summarizeGraph(graph).elements.filter((e) => e.id !== target.id);
    const review = await reviewer.review({
      currentTurn,
      currentTurnText,
      candidateUpdate: u,
      targetElement: target,
      nearbyActiveElements,
    });
    log.push({ targetElementId: u.targetElementId, decidability: review.decidability, decision: review.decidability === "DECIDABLE" ? review.decision : undefined, confidence: review.confidence, note: review.note });

    if (review.decidability === "NOT_DECIDABLE") {
      keptUpdates.push({ ...u, identityRelation: "uncertainSameElement" });
      addedUnresolved.push(toNotDecidableUnresolved(u));
      continue;
    }

    if (review.decision === "SAME_ELEMENT") {
      keptUpdates.push(u);
    } else {
      const localRef = `review-promoted-t${currentTurn}-${promotionSeq++}`;
      addedNewElements.push(toPromotedElement(u, localRef));
      if (review.decision === "SAME_REALITY_DIFFERENT_ELEMENT") {
        addedRelations.push(toPromotionRelation(u, localRef, target.confidence, review.suggestedRelationType));
      }
      // SEPARATE_REALITY: promoted with no relation to the target.
    }
  }

  return {
    output: {
      ...output,
      newElements: [...output.newElements, ...addedNewElements],
      updatedElements: keptUpdates,
      relations: [...output.relations, ...addedRelations],
      unresolvedCandidates: [...output.unresolvedCandidates, ...addedUnresolved],
    },
    log,
  };
}
