/**
 * HRI Voice Guide
 *
 * This file defines the permanent principles
 * for every observation generated by HRI.
 *
 * These rules are architecture rules,
 * not prompt rules.
 */

export const VOICE_GUIDE = {

  observeOnly: true,

  noDiagnosis: true,

  noJudgement: true,

  noAdvice: true,

  noPrediction: true,

  preserveUserLanguage: true,

  connectOnlyObservedFacts: true,

  neverInventMeaning: true,

  neverInventWish: true,

  leaveReflectionSpace: true,

} as const;